MODE_KEY = "PAYPAL_MODE"
CLIENT_ID_KEY = "PAYPAL_CLIENT_ID"
CLIENT_SECRET_KEY = "PAYPAL_CLIENT_SECRET"

DOMAIN = "paypal.com"

API_SUBDOMAIN = "api"
APIM_SUBDOMAIN = "api-m"
SANDBOX_SUBDOMAIN = "sandbox"

LIVE_URL = f"https://{API_SUBDOMAIN}.{DOMAIN}"
SANDBOX_URL = f"https://{API_SUBDOMAIN}.{SANDBOX_SUBDOMAIN}.{DOMAIN}"
